Created options menu and added master volume
toryjleo/Synthwave-Cycle pull request #145
Opened 2024-02-09 03:12 UTC by Jomkit

2024-02-09 15:32 UTC, toryjleo requested changes

2024-02-09 15:32 UTC, toryjleo commented on Assets/Scripts/UI/ChangeScene.cs
> +    [SerializeField] private VolumeScript volumeScript;
Is this used anywhere?

2024-02-09 15:32 UTC, toryjleo commented on Assets/loadAudioSettings.cs
> +public class loadAudioSettings : MonoBehaviour
```suggestion
public class LoadAudioSettings : MonoBehaviour
```
Make sure to change filename too

2024-02-09 15:32 UTC, toryjleo commented on Assets/loadAudioSettings.cs
> +    */
Delete these lines

2024-02-09 15:32 UTC, toryjleo commented on Assets/Scripts/UI/VolumeScript.cs
> +    }
Instead of saving and loading "MASTER_VOLUME" from the UI script, could you instead handle that logic in loadAudioSettings?
Feel free to give me your thoughts, but I imagine it might get a bit confusing if multiple classes are saving and loading this preference. It seems to me that the logic in VolumeScript shouldn't be tightly linked to _how_ we save and load said data.

2024-02-24 15:29 UTC, Jomkit commented on Assets/Scripts/UI/ChangeScene.cs
> +    [SerializeField] private VolumeScript volumeScript;
I don't think so, I'm gonna delete it

2024-02-24 15:32 UTC, Jomkit commented on Assets/loadAudioSettings.cs
> +public class loadAudioSettings : MonoBehaviour
Will do. Should I move it to a specific script folder too?

2024-02-24 15:33 UTC, Jomkit commented on Assets/loadAudioSettings.cs
> +    */
You got it king

2024-02-24 16:18 UTC, Jomkit commented on Assets/Scripts/UI/VolumeScript.cs
> +    }
Yep, so we ended up refactoring VolumeSliderScript (formerly VolumeScript) Save() and Load() methods so that the MASTER_VOLUME logic is handled in the AudioSettingController (formerly loadAudioSettings) script, and instead VolumeSliderScript.Save() and VolumeSliderScript.Load() just calls on that

2024-05-31 17:13 UTC, toryjleo approved these changes
lgtm

2024-07-09 12:59 UTC, closed without merging