Updated Enemy Spawning
toryjleo/Synthwave-Cycle pull request #157
Opened 2024-07-13 15:27 UTC by LiamMillerSE

Added Enum for enemy spawn location relative to the player Enemies now spawn in groups depending on location defined in Wave Implemented new spawning data for InTheirFinalMoments Note: All wave sequenced other than InTheirFinalMoments have been reset

2024-07-13 15:32 UTC, toryjleo requested changes

2024-07-13 15:32 UTC, toryjleo commented on Assets/Scripts/Enemies/EnemyPool.cs
> +    public Ai SpawnFromPool(Enemy tag, Vector3 position, Vector3 playerLocation)
Could you comment this method?

2024-07-24 12:57 UTC, toryjleo approved these changes

2024-08-17 15:28 UTC, Shadowmage77 approved these changes
Looks good!

2024-08-17 15:33 UTC, merged